USER_NAME := manna-harbour_miryoku

LTO_ENABLE = yes

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MAGIC_ENABLE = no
SPACE_CADET_ENABLE = no

OLED_ENABLE = yes
OLED_DRIVER = ssd1306
# RGBLIGHT_ENABLE = yes    # Enable WS2812 RGB underlight.
RGBLIGHT_ENABLE = no
